# Generated by Django 4.2.6 on 2023-10-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
