# Generated by Django 4.2.6 on 2023-10-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_pub',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
